language: haskell

branches:
  only:
    - master

before-install:
  - git clone https://github.com/GrammaticalFramework/gf-core.git
  - cd gf-core/src/runtime/c/
  - autoreconf -i
  - ./configure
  - make
  - make install
  - cd ../haskell-bind
  - cabal install
  - cd
  - cabal install cmdargs
  

install:
  - echo "installing gftest"

script:
  - echo "Hello world"