language: haskell

branches:
  only:
    - master

before_script:
  - git clone https://github.com/GrammaticalFramework/gf-core.git
  - cd gf-core/src/runtime/c/
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - cd ../haskell-bind
  - cabal install
  - cabal install cmdargs

script:
  - cd $TRAVIS_BUILD_DIR
  - cabal build